
### Create Tour
POST /api/v1/tours
@host: 127.0.0.1
@port: 3000
Content-type: application/json

{}

### Get All Tours 
# Filtering 
# ?duration[gte]=5&difficulty=easy&price[lte]=400
# Sorting
# ?sort=-price,ratingAverage
# Selecting Fields
#?fields=name,duration,price
GET /api/v1/tours?fields=name,duration,price
@host: 127.0.0.1
@port: 3000

### Get tour By Id
GET /api/v1/tours/66e4aeaaf24260e43a8d337b
@host: 127.0.0.1
@port: 3000

### Update Tour
PATCH /api/v1/tours/66e4aeaaf24260e43a8d337b
@host: 127.0.0.1
@port: 3000
Content-type: application/json

{
	"name": "Mountain silver",
	"price": 325
}

### Delete Tour
DELETE /api/v1/tours/66e5920ae1062484e582664b
@host: 127.0.0.1
@port: 3000