
### Create User
POST /api/v1/users
@host: 127.0.0.1
@port: 3000
Content-type: application/json

{
	"name": "River and mountain",
	"duration": 6,
	"difficulty": "easy",
	"price": 450
}

### Get All Users 
GET /api/v1/users
@host: 127.0.0.1
@port: 3000

### Get user By Id
GET /api/v1/users/5
@host: 127.0.0.1
@port: 3000

### Update User
PATCH /api/v1/users/1
@host: 127.0.0.1
@port: 3000
Content-type: application/json

{
	"name": "mountain",
	"duration": 6,
	"difficulty": "easy",
	"price": 450
}

### Delete User
DELETE /api/v1/users/9
@host: 127.0.0.1
@port: 3000